---
title: "W9 Code Along"
author: "Liu Yingzhe"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Slide 8

```{r, eval=TRUE,echo=TRUE}
library(tidyverse)
tidydata <- tribble(~country, ~year, ~cases, ~population,
                    "Afghanistan", 1999,745,19907071,
                    "Afghanistan", 2000, 2666, 20595360,
                    "Brazil", 1999, 37737, 172006362,
                    "Brazil", 2000, 80488, 174504898,
                    "China", 1999, 212258, 1272915272,
                    "China", 2000, 213766, 1280428583)
tidydata

```
```{r, eval=TRUE,echo=TRUE}
library(tidyverse)
nontidydata <- tribble(~country, ~year, ~rate,
                    "Afghanistan", 1999,"745/19907071",
                    "Afghanistan", 2000, "2666/20595360",
                    "Brazil", 1999, "37737/172006362",
                    "Brazil", 2000, "80488/174504898",
                    "China", 1999, "212258/1272915272",
                    "China", 2000, "213766/1280428583")
nontidydata

```
## slide 11
```{r, eval=TRUE,echo=TRUE}
nontidydata

```
```{r, eval=TRUE,echo=TRUE}
tidieddata <- nontidydata %>% separate (rate, into = c("cases","population"), sep = "/")
tidieddata
```
```{r, eval=TRUE,echo=TRUE}
newtidieddata <- tidieddata %>% pivot_longer (cols = cases:population, names_to = "measurement", values_to = "value")

newtidieddata

```
```{r, eval=TRUE,echo=TRUE}
df <- tribble(~id, ~bp1, ~bp2,
              "A", 100, 120,
              "B", 140, 115,
              "C", 120, 125
              )
df

```
```{r, eval=TRUE,echo=TRUE}
df %>% pivot_longer(
  cols= bp1:bp2,
  names_to = "measurement",
  values_to = "value"
)

```
```{r, eval=TRUE,echo=TRUE}
newtidieddata

```
```{r, eval=TRUE,echo=TRUE}
newtidieddata %>% pivot_wider(names_from="measurement", values_from="value")

```
```{r, eval=TRUE,echo=TRUE}
df <- tribble (~id, ~measurement, ~value,
               "A", "bp1", 100,
               "B", "bp1", 140,
               "B", "bp2", 115,
               "A", "bp2", 120,
               "A", "bp3", 105)
df

```
```{r, eval=TRUE,echo=TRUE}
df %>% pivot_wider(names_from = measurement, values_from = value)

```
## Challenge 

```{r, eval=TRUE,echo=TRUE}
library(tidyverse)
data("billboard")

billboard_long <- billboard %>%
  pivot_longer(cols = starts_with("wk"), 
               names_to = "week", 
               values_to = "rank", 
               values_drop_na = TRUE)
billboard_long %>% mutate(week = parse_number(week))

view(billboard_long)

library(ggplot2)
ggplot(billboard_long, aes(x = week, y = rank)) +
  geom_line()

```
```{r}
cms_patient_experience_new <- cms_patient_experience %>%
  pivot_wider(
    id_cols = starts_with("org"),
              names_from = measure_cd, 
              values_from = prf_rate)
cms_patient_experience_new
```

